### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by joostdam** [DEAN-ngo/elimupi#110] opened 2023-06-01 08:51 UTC
When connecting a wireless device to the new Elimupi (with the latest image 3.3.0) the devices (tested on android phone and tablet with Chrome browsers) cannot open the interface. 

I can access the pages with my laptop where I configured the hosts file manually. 

That suggest that the problem is with the DNS of the elimupi.

**Comment by ltoning** [comment] 2023-06-08 08:28
Seems that DNS ( dnsmasq) is delayed or interfered when the Pi is booting up.
This seems to be caused by the extensive loading of the scratch-gui via nmp.

**Comment by ltoning** [comment] 2023-06-16 16:25
@joostdam shall we close this one as the issue its caused by having a LAN connection via ethernet?
DNS resolution via AP/Wifi will not work in that case.

**Comment by joostdam** [comment] 2023-06-16 19:15
@ltoning, it worked in the previous version and is very useful when testing. If we can have this feature back, I prefer that.

**Comment by ltoning** [comment] 2023-06-23 13:34
@joostdam I fully agree with this.
 I will get a fix out to address this issue.

**Comment by alonsovidales** [comment] 2023-11-04 17:33
I think that the root cause was not loading the `scratch-gui` and it was fixed, nope? if not let me know and I can take a look at it 👍

**Comment by ltoning** [comment] 2023-11-05 05:55
Root cause of this issue was a mixed setup of using dhcpdcd and udhcpcd together and having nog forwarding rules.
Bug Fixed in #117

**Comment by ltoning** [comment] 2023-11-05 05:55
closing

**Closed by ltoning** 2023-11-05 05:55 UTC
Labels: bug
